#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running auto-format script..."
node scripts/auto-format.mjs
status=$?

if [ $status -ne 0 ]; then
  echo "Auto-format script failed. Aborting commit."
  exit $status
fi

git add -A
